### PR TITLE
convert plugins with hyphenated names to camel case

### PR DESCRIPTION
**Pull request by dominictarr**
once this is merged I can (finally) roll out https://github.com/ssbc/ssb-device-address

### CODE REVIEW

**Comment by cryptix** [comment]
humor me, please: why are hypens in plugin names a problem? I know I stumbled over this as well when I worked on ssb-plugins2 some weeks ago.

**Comment by christianbundy** [comment]
IIRC, you'd have a hard time calling them with `sbot.device-address.getAddress()` because `-` is an invalid token in property names. In ssb-blob-content I just have the name set as blobContent, but I wouldn't mind this being automatic.

**Comment by cryptix** [comment]
okay thanks @christianbundy. I guessed it was about `sbot['why-would-anyone'].things()` but wasn't sure if there was another reason.

**Comment by christianbundy** [comment]
Yeah, I suppose it isn't an *invalid* token in property names, but accessing those props is a bit hacky.

**Comment by dominictarr** [comment]
@cryptix yeah, just translating relevant conventions. plugins are typically published to npm, which allows hyphens but not camel case in module names. js names can be camel case but not hypens etc. luckily either camel case or hyphens preserves sufficient context to convert between them... unlike ambigiouscase the few of which you see in ssb are notmyfault.

**Comment by dominictarr** [comment]
merged into 5.0.0

**Comment by cryptix** [comment]
hrm... turns out my comment above was not hypothetical at all: https://github.com/Happy0/ssb-chess/pull/82

**Pull request closed without merging**
