### PR TITLE
convert new Buffer() to Buffer.from everywhere

### PR DESCRIPTION
**Pull request by mixmix**
what it says on the tin.

apparently this is a minor security win

### CODE REVIEW

**Comment by dominictarr** [comment]
there is something wrong with the tests... test/close errors

**Comment by staltz** [comment]
@dominictarr What's wrong with the tests? The logs look similar with what's on `master` right now: 

- This PR: https://travis-ci.org/ssbc/secret-stack/jobs/600618843
- Master: https://travis-ci.org/ssbc/secret-stack/jobs/568272498

So if anything it should be an orthogonal issue to this PR.

**Comment by dominictarr** [comment]
that's strange because I get this error:

```

TypeError: read is not a function
    at next (/home/dominic/c/secret-stack/node_modules/pull-stream/sinks/drain.js:16:11)
    at sink (/home/dominic/c/secret-stack/node_modules/pull-stream/sinks/drain.js:37:9)
    at sink (/home/dominic/c/secret-stack/node_modules/muxrpc/pull-weird.js:61:7)
    at Object.exports.pipeToStream (/home/dominic/c/secret-stack/node_modules/muxrpc/util.js:138:5)
    at PacketStreamSubstream.stream.read (/home/dominic/c/secret-stack/node_modules/muxrpc/stream.js:76:18)
    at PacketStream._onstream (/home/dominic/c/secret-stack/node_modules/packet-stream/index.js:228:11)
    at PacketStream.write (/home/dominic/c/secret-stack/node_modules/packet-stream/index.js:135:41)
    at /home/dominic/c/secret-stack/node_modules/muxrpc/pull-weird.js:56:15
    at /home/dominic/c/secret-stack/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/dominic/c/secret-stack/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
```
did the tests pass when you ran them?

**Comment by staltz** [comment]
@dominictarr Yes both master and this PR branch tests pass on my computer and look exactly like Travis.

My computer:

```
$ npm version

{ 'secret-stack': '6.3.0',
  npm: '6.4.1',
  ares: '1.15.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.15.3',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.51',
  zlib: '1.2.11' }
```

```
$ uname -a

Linux xor 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

The `whynoclose` branch you made also passes all tests on my computer, the logs look like:

```
TEST/CLOSE
net:localhost:49405~shs:alicv2bzIOOfBk2gXlF/WeQaQJJkyFQbeEYt8G42L/k=
CONNECT 1 null
CONNECT 2 null
closed
```

Perhaps you're using an old version of Node and there's something like a trailing comma or new syntax that doesn't run on your Node?

**Comment by staltz** [comment]
> But before, could you add an "engines" entry in the package.json saying that this only supports Node.js version 5 and higher?

We should do this too. Maybe in this PR or after.

**Comment by dominictarr** [comment]
I'm not running a version that is _that old_ I know I like the old ways but not that old! I stayed on 8 for ages...

I tried running the tests on later nodes, 11, and 13 and I get the same test failure, so it's not my node version!

But merge, checking out 462be58cd984557de2cf32636780238bd064788d this was already broken (somehow...?) must just be on my computer though

**Pull request merged**
