### PR TITLE
update to use multiserver

### PR DESCRIPTION
**Pull request by dominictarr**
@arj03's changes

### CODE REVIEW

**Comment by dominictarr** [comment]
@arj03 have you tested this in scuttlebot?

I notice that you are not passing any options into the multiserver instance you are creating here,
if I recall, that will create it as a client only
https://github.com/ssbc/secret-stack/pull/10/files#diff-168726dbe96b3ce427e7fedce31bb0bcR84

it might be better to add a `protocol` field to the address object, rather than detect `.onion` in the hostname,
although this seems like a reasonable approach with the current secret-stack design...

but when we get to my proposed gossip refactor `%vB5bEoo/Sg8e1OVCX0A1iQjoQE4uhteRAhz/oCBUzNg=.sha256`  we can make everything use multiserver addresses directly

**Comment by dominictarr** [comment]
i got this error trying to run this in sbot

```
/home/dominic/c/multiserver/node_modules/secret-handshake/handshake.js:89
        authorize(state.remote.public, function (err, auth) {
        ^

TypeError: authorize is not a function
    at Object.cb (/home/dominic/c/multiserver/node_modules/secret-handshake/handshake.js:89:9)
    at drain (/home/dominic/c/multiserver/node_modules/pull-reader/index.js:39:14)
    at more (/home/dominic/c/multiserver/node_modules/pull-reader/index.js:51:13)
    at /home/dominic/c/multiserver/node_modules/pull-reader/index.js:62:9
    at /home/dominic/c/multiserver/node_modules/pull-reader/index.js:20:7
    at drain (/home/dominic/c/multiserver/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/dominic/c/multiserver/node_modules/stream-to-pull-stream/index.js:150:5)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```

**Comment by dominictarr** [comment]
okay, that was a problem in multiserver

**Comment by dominictarr** [comment]
okay, this now runs in scuttlebot, at least, I merged these changes and scuttlebot still works. I would like to try it directly through a tor pub before merging. Can you setup a pub on tor, so we can confirm it works?

**Comment by arj03** [comment]
Agree with the onion bit, guess it's good enough for now. Multiserver is really nifty in that its open ended and we can just multiple protocols.

Thanks you for reviewing the patches, the reason why I didn't create a pull request was that its really hard for me to see if I broke something or not. Seems like we have another onion tester, so we should get this worked relatively quickly I think :)

**Comment by arj03** [comment]
That last commit is what makes it work. I now have it working together with the hacky invite patch for scuttlebot + updated multiserver.

If you want to test:

sbot invite.accept 355ij5sv346bpih2.onion:8008:@lbocEWqF2Fg6WMYLgmfYvqJlMfL7hiqVAV6ANjHWNw8=.ed25519~t7UhT15nIaDoWbdTZHVg4HJ1VHcmtl/FOplSyQfn03E=

**Comment by arj03** [comment]
There is one more thing needed for connections to come through and thats:

@ -130,7 +130,8 @@ module.exports = function (opts) {
       var peers = api.peers = {}
 
       var ms = MultiServer([
-        [Net({port: port}), shs]
+        [Net({port: port}), shs],
+        [Onion({}), shs]
       ])
 
       var server = ms.server(setupRPC)

Which means that now the server functions of my onion plugin will start getting called (and that's not working properly), but it's not really needed. So if I just put in a return there I'll get gossip connect to my tor sbot server. It's just strange that it looks at the server for protocols to do gossipping?

**Comment by dominictarr** [comment]
okay, trying to get this working - mostly getting ` Error: Negotiation Error (5)`

**Comment by dominictarr** [comment]
still some work to do here to get the tests passing. most of that is from migrating to multiserver though, currently addresses are returned as `{host, port, key}` but it would be better to just use multiserver addresses

**Comment by dominictarr** [comment]
getting the secret-stack tests passing was fairly easy, but adding that into scuttlebot breaks the gossip tests,
... just because addresses do not parse as it expects

**Comment by dominictarr** [comment]
okay I've merged this as a breaking change, just gotta get scuttlebot working with it...

secret-stack@3.0.0

**Comment by arj03** [comment]
Thanks! I'll have a look at the branch tonight.

**Pull request merged**
